-- A. 
ALTER TABLE JOB_HISTORY
ADD CONSTRAINT FK_EMP_ID
FOREIGN KEY (Employee_ID)
REFERENCES Employees(Employee_ID)
ON DELETE CASCADE;


-- B.
ALTER TABLE Employees
ADD CONSTRAINT FK_DPT_ID
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID)
ON DELETE SET NULL;