USE DUMMYDB;
-- WAY -1 

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY Salary DESC
LIMIT 1 OFFSET 3;


-- WAY -2 
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = (
	SELECT DISTINCT MAX(SALARY)
	FROM EMPLOYEES
    WHERE SALARY< (SELECT DISTINCT MAX(SALARY)
	FROM EMPLOYEES
    WHERE SALARY<(SELECT DISTINCT MAX(SALARY)
	FROM EMPLOYEES
    WHERE SALARY ))
);

-- 3rd LOWEST SALARY :
-- WAY -1 
-- WAY -2 
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = (
	SELECT DISTINCT MIN(SALARY)
	FROM EMPLOYEES
    WHERE SALARY> (SELECT DISTINCT MIN(SALARY)
	FROM EMPLOYEES
    WHERE SALARY>(SELECT DISTINCT MIN(SALARY)
	FROM EMPLOYEES
    WHERE SALARY ))
)
LIMIT 1;


-- WAY -2
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY Salary asc
LIMIT 1 OFFSET 3;



SELECT *FROM EMPLOYEES WHERE hire_date  ORDER BY hire_date ASC ;


SELECT FIRST_NAME
FROM EMPLOYEES
WHERE hire_date > (
    SELECT hire_date
    FROM EMPLOYEES
    WHERE FIRST_NAME = 'Steven'
    ORDER BY hire_date ASC
    LIMIT 1
)
ORDER BY hire_date ASC
LIMIT 1;




-- the third highest salary 
WITH RANK_SALARY AS
(
	SELECT  FIRST_NAME,SALARY,
		(SELECT COUNT(DISTINCT(SALARY)) FROM EMPLOYEES E2 WHERE E2.SALARY > E1.SALARY)+1 AS SALARY_RANK_DESC 
    FROM EMPLOYEES E1
    )

SELECT *
FROM RANK_SALARY
WHERE SALARY_RANK_DESC=3
 LIMIT 1;


--  the third lowest salary 3D SALARY 
WITH RANK_SALARY AS(
 SELECT FIRST_NAME, SALARY ,
 (SELECT COUNT(DISTINCT(SALARY)) FROM EMPLOYEES E2 WHERE E2.SALARY < E1.SALARY)+1 AS SALARY_RANK_ASC 
 FROM EMPLOYEES E1
 )
 SELECT *
 FROM RANK_SALARY
 WHERE SALARY_RANK_ASC = 3
 LIMIT 1
 
