
SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID;


SELECT * FROM DEPARTMENTS;
-- WAY -1 
SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS ON  EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID;

-- WAY-2 - BUT THIS NOT GOOD
SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS  USING( DEPARTMENT_ID); 


-- join
-- INNER JOIN
SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
 INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID;
 
 -- LEFT JOIN
SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID;
 
 -- RIGHT JOIN 
 SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
 RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID;
 
 -- CROSS JOIN
 SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
 CROSS JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID;
 
 
 -- JOIN MANAGER AND EMPLOYEES NAME:
 SELECT  M.FIRST_NAME AS MANAGER_NAME ,e.FIRST_NAME AS EMPLOYEES_NAME 
 FROM EMPLOYEES AS e
	JOIN EMPLOYEES AS m
    ON E.EMPLOYEE_ID = m.MANAGER_ID;
    
-- Print the department name where has no employees

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS AS D
	LEFT JOIN EMPLOYEES AS E
		ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NULL;
        

-- print avarage and current salary detween difference : 

SELECT 
E.FIRST_NAME,
E.SALARY,
(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID)- E.SALARY AS NEW_COUNT

FROM EMPLOYEES AS E
JOIN DEPARTMENTS AS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- print min n salary theke beshi jader salary ache oigualr depat & salary :
SELECT DEPARTMENT_NAME,MIN(SALARY),AVG(SALARY)
FROM EMPLOYEES
JOIN  DEPARTMENTS
ON EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING min(EMPLOYEES.SALARY) > 5000

-- join common table expreastion :

WITH DEPARTMENT_SALARY AS (
    SELECT 
        D.DEPARTMENT_NAME,
        -- SALARY AS MAIN_SALARY
        MIN(E.SALARY) AS MIN_SALARY,
        AVG(E.SALARY) AS AVG_SALARY 
    FROM EMPLOYEES AS E
    JOIN DEPARTMENTS AS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_NAME
)

SELECT 
    DEPARTMENT_NAME,
    -- MAIN_SALARY,
    MIN_SALARY,
    AVG_SALARY
FROM DEPARTMENT_SALARY 
WHERE MIN_SALARY > 3000;


SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;
    