CREATE DATABASE STUDENT_MANAGMENT_SYS;

USE STUDENT_MANAGMENT_SYS;

CREATE TABLE STUDENT(
    ROLL VARCHAR(4) NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE BOOK(
    BOOK_ID VARCHAR(4) NOT NULL PRIMARY KEY,
    BOOK_NAME VARCHAR(20) NOT NULL,
    BOOK_GNENERAL VARCHAR(20) NOT NULL
)

CREATE TABLE LAIBRARIAN(
    LIB_ID VARCHAR(4) NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
)

CREATE TABLE BORROW(
    WHO_BORROW_ID VARCHAR(4) NOT NULL,
    WHICH_BOOK_ID VARCHAR(4) NOT NULL,
    BORROW_DATE DATE NOT NULL,
    RETURN_DATE DATE ,

    FOREIGN KEY (WHICH_BOOK_ID) REFERENCES BOOK(BOOK_ID),
    FOREIGN KEY (WHO_BORROW_ID) REFERENCES STUDENT(ROLL),
    PRIMARY KEY (WHO_BORROW_ID, WHICH_BOOK_ID)

)


CREATE TABLE PERMISSON(
    WHICH_BOOK_ID VARCHAR(4) NOT NULL,
    WHO_PERMITED_LIB_ID VARCHAR(4),


    FOREIGN KEY (WHICH_BOOK_ID) REFERENCES BOOK(BOOK_ID),
    FOREIGN KEY (WHO_PERMITED_LIB_ID) REFERENCES LAIBRARIAN(LIB_ID),
    PRIMARY KEY (WHICH_BOOK_ID, WHO_PERMITED_LIB_ID)
)